allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: false
  msgpackr-extract: false
  prisma: set this to true or false
  unrs-resolver: false
  workerd: false
